ARG DISTRIBUTION_VERSION
# DISTRIBUTION_VERSION: 2.6 2.7 3.1-3.8 edge
FROM alpine:${DISTRIBUTION_VERSION}

ARG SOURCE

WORKDIR /app
COPY ./${SOURCE} /app/.

ARG LUA_VERSION
# DISTRIBUTION_VERSION: 3.1
# LUA_VERSION: 5.1-5.2
# DISTRIBUTION_VERSION: > 3.1
# LUA_VERSION: 5.1-5.3
ENV LUA_PACKAGE lua${LUA_VERSION}

RUN apk update
RUN apk add ${LUA_PACKAGE}

ENV LUA_EXEC=lua${LUA_VERSION}
ENTRYPOINT $LUA_EXEC compute.lua
